FROM node:12 as builder

WORKDIR /app

COPY . /app

RUN npm i && npm run build

FROM nginx:stable

WORKDIR /

COPY --from=builder /app/build /var/www

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

